Problem: cannot get backup-mnemonics from existing wallet in c++ bind…
crypto-com/defi-wallet-core-rs pull request #542
Opened 2022-08-07 09:58 UTC by leejw51crypto

…ing (fix #541)

Solution: add get-backup-mnemonics

2022-08-08 01:12 UTC, tomtau approved these changes

2022-08-08 01:15 UTC, tomtau requested changes
linux + windows build fail

2022-08-08 01:26 UTC, leejw51crypto commented
i'll fix asap

2022-08-09 01:15 UTC, tomtau approved these changes

2022-08-09 01:15 UTC, merged