Problem: not updated for version 0.3.1 (fix #719)
crypto-com/defi-wallet-core-rs pull request #720
Opened 2022-12-06 09:01 UTC by leejw51crypto

Solution: update to 0.3.1

2022-12-06 09:04 UTC, tomtau requested changes
maybe you can update the other Cargo.toml and the changelog?

2022-12-06 09:06 UTC, leejw51crypto commented
ok

2022-12-07 06:32 UTC, tomtau approved these changes

2022-12-07 06:32 UTC, tomtau commented on CHANGELOG.md
>  - Minting C++ Example
is the changelog complete?

2022-12-07 06:33 UTC, leejw51crypto commented on CHANGELOG.md
>  - Minting C++ Example
i'll add

2022-12-07 06:39 UTC, damoncro commented
Please update Cargo.lock as well.

2022-12-07 06:42 UTC, leejw51crypto commented
ok

2022-12-07 06:44 UTC, SHH-HaoZhang approved these changes

2022-12-07 06:50 UTC, merged